# Generated by Django 5.1.5 on 2025-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
